---
title: Paint Box
hero_image: images/banner.png
listed: true
copyedit: false
description: Maak je eigen teken programma
version: 4.1.0
last_tested: 2018/11/30
steps:
  - title: Inleiding
  - title: Een potlood maken
  - title: Kleurpotloden
  - title: 'Uitdaging: meer potloden'
    challenge: true
  - title: Fouten maken
  - title: De potlooddikte wijzigen
  - title: 'Uitdaging: toetsenbord opdrachten'
    challenge: true
  - title: 'Wat nu?'
