---
hero_image: images / banner.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-2, phys-comp-0, manufacture-0, community-0
title: Paint Box
description: Leer hoe je je eigen tekenprogramma maakt.
original_url: https://codeclubprojects.org/en-GB/scratch/paint-box
interests: 'kunst & ontwerp'
technologies: scratch
site_areas: codeclub, scratch
steps:
  - 
    title: Inleiding
  - 
    title: Wat heb je nodig
  - 
    title: Een potlood maken
  - 
    title: Kleurpotloden
  - 
    title: Fouten maken
  - 
    title: De potlooddikte wijzigen
  - 
    title: 'Uitdaging: snelkoppelingen'
  - 
    title: 'Uitdaging: meer potloden'
