---
title: Paint Box
hero_image: images/banner.png
listed: true
copyedit: false
description: Leer hoe je je eigen tekenprogramma maakt.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Wat heb je nodig
  - 
    title: Een potlood maken
  - 
    title: 'Kleurpotloden'
    challenge: true
  - 
    title: Fouten maken
  - 
    title: De potlooddikte wijzigen
  - 
    title: 'Uitdaging: snelkoppelingen'
    challenge: true
  - 
    title: 'Uitdaging: meer potloden'
