---
title: Paint Box
hero_image: images/banner.png
listed: true
copyedit: false
description: Maak je eigen teken programma
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Inleiding
  - 
    title: Een potlood maken
  - 
    title: Kleurpotloden
  - 
    title: 'Challenge: more pencils'
    challenge: true
  - 
    title: Fouten ongedaan maken
  - 
    title: De potlooddikte wijzigen
  - 
    title: 'Challenge: keyboard commands'
    challenge: true
  - 
    title: 'Wat kun je verder nog doen?'
