hero_image: images/banner.png
listed: true
copyedit: false
description: Learn how to make your own paint program.
version: 4.0.0
last_tested: 2018-11-30
steps: 
- title: Introduction
- title: Making a pencil
- title: Coloured pencils
- title: Making mistakes
- title: 'Challenge: shortcuts'
  challenge: true
- title: Changing the pencil width
- title: 'Challenge: more pencils'
  challenge: true
- title: 'What next?'