---
title: Коробка для рисования
hero_image: images/banner.png
listed: true
copyedit: false
description: Сделай свою собственную программу для рисования
version: 4.1.0
last_tested: 30-11-2018
steps:
- title: Введение
- title: Сделай карандаш
- title: Цветные карандаши
  completion:
  - engaged
- title: 'Задача: больше карандашей'
  challenge: true
- title: Отмена ошибочных действий
- title: Измени ширину карандаша
  completion:
  - internal
- title: 'Задача: команды на клавиатуре'
  challenge: true
- title: Что дальше?
