---
title: Коробка для рисования
hero_image: images/banner.png
listed: true
copyedit: false
description: Сделай свою собственную программу для рисования
version: 4.1.0
last_tested: 30-11-2018
steps:
  - 
    title: Введение
  - 
    title: Сделай карандаш
  - 
    title: Цветные карандаши
  - 
    title: 'Задача: горячие клавиши'
    challenge: true
  - 
    title: Отмена ошибочных действий
  - 
    title: Измени ширину карандаша
  - 
    title: 'Challenge: keyboard commands'
    challenge: true
  - 
    title: 'Что дальше?'
