---
title: Програм за цртање
hero_image: images/banner.png
listed: true
copyedit: false
description: Направи сопствени програм за цртање
version: 4.0.0
last_tested: 2018-11-30
steps:
  - 
    title: Увод
  - 
    title: Направи оловку
  - 
    title: Бојице
  - 
    title: 'Изазов: Пречице'
    challenge: true
  - 
    title: Поништи грешке
  - 
    title: Промени дебљину оловке
  - 
    title: 'Изазов: Више бојица'
    challenge: true
  - 
    title: 'Шта је следеће?'
