---
title: ペイントボックス
hero_image: images/banner.png
listed: true
copyedit: false
description: お絵かきができるプログラムを作りましょう
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: はじめに
  - 
    title: 鉛筆を作る
  - 
    title: 色鉛筆
    completion:
      - engaged
  - 
    title: 'Challenge: more pencils'
    challenge: true
  - 
    title: 間違いを元に戻す
  - 
    title: 鉛筆の幅を変える
    completion:
      - internal
  - 
    title: 'Challenge: keyboard commands'
    challenge: true
  - 
    title: 次は何？
