---
title: Hộp sơn
hero_image: images / banner.png
listed: true
copyedit: false
description: Làm chương trình sơn của riêng bạn
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Giới thiệu
  - 
    title: Làm bút chì
  - 
    title: Bút chì màu
  - 
    title: 'Thử thách: phím tắt'
    challenge: true
  - 
    title: Hoàn tác sai lầm
  - 
    title: Thay đổi chiều rộng bút chì
  - 
    title: 'Thử thách: thêm bút chì'
    challenge: true
  - 
    title: 'What next?'
