---
hero_image: images / banner.png
theme: bənövşəyi
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, dizayn-0, proqramlaşdırma-1, phys-comp-0, istehsal-0, icma-0
title: Paint Box
description: Öz boya proqramınızı necə etmək barədə məlumat əldə edin.
original_url: https://codeclubprojects.org/en-GB/scratch/paint-box
interests: incəsənət
technologies: cızıq
site_areas: layihələr
hardware: ''
software: cızıq
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Giriş
  - 
    title: Nə lazımdır?
  - 
    title: Qələm edilməsi
  - 
    title: Rəngli qələmlər
  - 
    title: Səhv etmək
  - 
    title: Qələmin genişliyini dəyişdirmək
  - 
    title: 'Çağırış: qısa yollar'
  - 
    title: 'Çağırış: daha çox qələm'
