---
title: Caixa de Pintura
hero_image: imagens/banner.png
listed: true
copyedit: false
description: Faz o teu próprio programa de pintura
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Caixa de Pintura
  - 
    title: Criar um lápis
  - 
    title: Lápis coloridos
  - 
    title: 'Desafio: atalhos'
    challenge: true
  - 
    title: Desfazer erros
  - 
    title: Mudar a grossura do lápis
  - 
    title: 'Desafio: Mais lápis'
    challenge: true
  - 
    title: 'O que se segue?'
