---
title: Caixa de Pintura
hero_image: images/banner.png
listed: true
copyedit: false
description: Neste projeto vais criar o teu proprio programa de desenho!
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Caixa de Pintura
  - 
    title: Make a pencil
  - 
    title: Coloured pencils
  - 
    title: 'Challenge: shortcuts'
    challenge: true
  - 
    title: Undo mistakes
  - 
    title: Change the pencil width
  - 
    title: 'Challenge: more pencils'
    challenge: true
  - 
    title: 'What next?'
