---
title: 颜料盒
hero_image: images/banner.png
listed: true
copyedit: false
description: 学习如何制作你自己的绘图程序。
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: 介绍
  - 
    title: 制作铅笔
  - 
    title: 彩笔
  - 
    title: '出错'
    challenge: true
  - 
    title: 更改笔尖宽度
  - 
    title: 挑战：快捷键
  - 
    title: '挑战：更多画笔'
    challenge: true
  - 
    title: Test yourself
  - 
    title: 'What next?'
