---
title: Program za bojanje
hero_image: images/banner.png
listed: true
copyedit: false
description: U ovom ćeš projektu izraditi vlastiti program za bojanje!
version: 4.1.0
last_tested: 2018-30-01
steps:
  - 
    title: Sretan rođendan
  - 
    title: Make a pencil
  - 
    title: Coloured pencils
  - 
    title: 'Challenge: shortcuts'
    challenge: true
  - 
    title: Undo mistakes
  - 
    title: Change the pencil width
  - 
    title: 'Challenge: more pencils'
    challenge: true
  - 
    title: Test yourself
  - 
    title: 'What next?'
