---
title: Caja de pintura
hero_image: images/banner.png
listed: true
copyedit: false
description: Realiza tu propio programa de pintura
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Introducción
  - 
    title: Make a pencil
  - 
    title: Coloured pencils
  - 
    title: 'Challenge: shortcuts'
    challenge: true
  - 
    title: Undo mistakes
  - 
    title: Change the pencil width
  - 
    title: 'Challenge: more pencils'
    challenge: true
  - 
    title: 'What next?'
