---
title: Bocs Paentio
hero_image: images/paint-box.png
listed: true
copyedit: false
description: Dysga sut i greu rhaglen paentio dy hunan.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Creu pensil
  - 
    title: Pensiliau lliw
  - 
    title: 'Her: gorchmynion y bysellfwrdd'
    challenge: true
  - 
    title: Dadwneud camgymeriadau
  - 
    title: Newid lled y pensil
  - 
    title: 'Challenge: keyboard commands'
    challenge: true
  - 
    title: 'Beth nesaf?'
