---
title: Bocs Paentio
hero_image: images/paint-box.png
listed: true
copyedit: false
description: Dysga sut i greu rhaglen paentio dy hunan.
version: 3
last_tested: 2017-01-01
steps:
- title: Cyflwyniad
  completion: engaged
- title: Creu pensil
- title: Pensiliau lliw
- title: 'Her: mwy o bensiliau'
  challenge: true
- title: Dadwneud camgymeriadau
  completion: internal
- title: Newid lled y pensil
- title: 'Her: gorchmynion y bysellfwrdd'
  challenge: true
- title: Profwch eich hun
- title: Beth nesaf?
