hero_image: images/paint-box.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Farbkasten
description: In diesem Projekt wirst Du Dein eigenes Zeichen-Programm entwickeln!
original_url: https://projects.raspberrypi.org/en/projects/paint-box
interests: art
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Einführung
- title: Einen Bleistift entwerfen
- title: Farbige Stifte
- title: Fehler machen
- title: Die Stift-Dicke ändern
- title: "Herausforderung: Tastenkürzel"
- title: "Herausforderung: Mehr Stifte"