---
title: Malkasten
hero_image: images/banner.png
listed: true
copyedit: false
description: Mach dein eigenes Malprogramm
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Einleitung
  - 
    title: Erzeuge einen Stift
  - 
    title: Buntstifte
    completion:
      - engaged
  - 
    title: 'Challenge: more pencils'
    challenge: true
  - 
    title: Fehler rückgängig machen
  - 
    title: Die Stiftdicke ändern
    completion:
      - internal
  - 
    title: 'Challenge: keyboard commands'
    challenge: true
  - 
    title: Wie geht es weiter?
