---
title: Malkasten
hero_image: images/banner.png
listed: true
copyedit: false
description: Mach dein eigenes Malprogramm
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Buntstifte
  - 
    title: 'Zusatzaufgabe: Tastenkürzel'
    challenge: true
  - 
    title: Fehler machen
  - 
    title: Die Stiftdicke ändern
  - 
    title: 'Zusatzaufgabe: mehr Stifte'
    challenge: true
  - 
    title: 'Zusatzaufgabe: mehr Stifte'
  - 
    title: 'What next?'
