---
title: Malkasten
hero_image: images/banner.png
listed: true
copyedit: false
description: Lerne dein eigenes Malprogramm zu machen.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Einen Stift machen
  - 
    title: 'Buntstifte'
    challenge: true
  - 
    title: Fehler machen
  - 
    title: Die Stiftdicke ändern
  - 
    title: 'Zusatzaufgabe: Tastenkürzel'
    challenge: true
  - 
    title: 'Zusatzaufgabe: mehr Stifte'
