---
title: Malkasten
hero_image: images/banner.png
listed: true
copyedit: false
description: Mach dein eigenes Malprogramm
version: 4.1.0
last_tested: 2018-11-30
steps:
  - title: Einleitung
  - title: Erzeuge einen Stift
  - title: Buntstifte
  - title: 'Aufgabe: mehr Stifte'
    challenge: true
  - title: Fehler ausbessern
  - title: Die Stiftdicke ändern
  - title: 'Aufgabe: Tasten-Kürzel'
    challenge: true
  - title: 'Wie geht es weiter?'
