---
hero_image: images/banner.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-2, phys-comp-0, manufacture-0, community-0
title: Malkasten
description: Lerne dein eigenes Malprogramm zu machen.
original_url: https://codeclubprojects.org/en-GB/scratch/paint-box
interests: 'art&design'
technologies: scratch
site_areas: codeclub, scratch
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Einen Stift machen
  - 
    title: Buntstifte
  - 
    title: Fehler machen
  - 
    title: Die Stiftdicke ändern
  - 
    title: 'Zusatzaufgabe: Tastenkürzel'
  - 
    title: 'Zusatzaufgabe: mehr Stifte'
