---
title: Cutia cu culori
hero_image: images/banner.png
listed: true
copyedit: false
description: Creează-ți propriul program de desenat
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Introducere
  - 
    title: Creează un creion
  - 
    title: Creioane colorate
  - 
    title: 'Provocare: scurtături'
    challenge: true
  - 
    title: Anulează greșelile
  - 
    title: Schimbă grosimea creionului
  - 
    title: 'Provocare: mai multe creioane'
    challenge: true
  - 
    title: 'What next?'
