---
title: Lousa Mágica
hero_image: images/banner.png
listed: true
copyedit: false
description: Faça o seu próprio programa de pintura
version: 4.1.0
last_tested: 2018-30-01
steps:
  - 
    title: Lousa Mágica
  - 
    title: Make a pencil
  - 
    title: Lápis coloridos
  - 
    title: 'Desafio: Atalhos'
    challenge: true
  - 
    title: Undo mistakes
  - 
    title: Change the pencil width
  - 
    title: '--- /challenge ---'
    challenge: true
  - 
    title: 'Desafio: Criar mais blocos'
