---
title: Lousa Mágica
hero_image: images/banner.png
listed: true
copyedit: false
description: Faça o seu próprio programa de pintura
version: 4.1.0
last_tested: 2018-30-01
steps:
  - 
    title: Introdução
  - 
    title: Crie um lápis
  - 
    title: Lápis coloridos
  - 
    title: 'Challenge: more pencils'
    challenge: true
  - 
    title: Desfazer erros
  - 
    title: Mudando a espessura do lápis
  - 
    title: 'Desafio: comandos de teclado'
    challenge: true
  - 
    title: 'E agora?'
