---
title: Lousa Mágica
hero_image: images/banner.png
listed: true
copyedit: false
description: Neste projeto, você irá fazer seu próprio programa de pintura!
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Lousa Mágica
  - 
    title: Make a pencil
  - 
    title: Coloured pencils
  - 
    title: 'Challenge: shortcuts'
    challenge: true
  - 
    title: Undo mistakes
  - 
    title: Change the pencil width
  - 
    title: 'Challenge: more pencils'
    challenge: true
  - 
    title: 'What next?'
