---
hero_image: images/banner.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Caixa de pintura
description: Aprenda a fazer seu próprio programa de pintura.
original_url: https://codeclubprojects.org/en-GB/scratch/paint-box
interests: art
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: O que você precisará
  - 
    title: Fazendo um lápis
  - 
    title: Lápis coloridos
  - 
    title: Fazendo rascunhos
  - 
    title: Alterando a espessura do lápis
  - 
    title: 'Desafio: atalhos'
  - 
    title: 'Desafio: mais lápis'
