---
hero_image: تصاویر / banner.png
theme: وایلیٹ
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1، ڈیزائن-0، پروگرامنگ -1، فیز-کمپ-0، تیاری-0، کمیونٹی-0
title: پینٹ باکس
description: اپنے پینٹ پروگرام بنانے کا طریقہ سیکھیں.
original_url: https://codeclubprojects.org/en-GB/scratch/paintbox
interests: آرٹ
technologies: خرگوش
site_areas: منصوبوں
hardware: ''
software: خرگوش
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: تعارف
  - 
    title: آپ کی ضرورت ہو گی
  - 
    title: پنسل بنانا
  - 
    title: رنگ پنسل
  - 
    title: غلطیاں کرنا
  - 
    title: پینسل چوڑائی کو تبدیل کرنا
  - 
    title: 'چیلنج: شارٹ کٹس'
  - 
    title: 'چیلنج: زیادہ پنسل'
