---
title: Paint box
hero_image: images/banner.png
listed: true
copyedit: false
description: Buatlah program lukis kamu sendiri
version: 4.1.0
last_tested: 2018-30-01
steps:
  - 
    title: Pengantar
  - 
    title: Make a pencil
  - 
    title: Pensil berwarna
  - 
    title: 'Tantangan: pintasan'
    challenge: true
  - 
    title: Undo mistakes
  - 
    title: Change the pencil width
  - 
    title: 'Tantangan: pensil tambahan'
    challenge: true
  - 
    title: 'What next?'
