---
title: Paint box
hero_image: images/banner.png
listed: true
copyedit: false
description: Buatlah program lukis kamu sendiri
version: 4.1.0
last_tested: 2018-30-01
steps:
  - 
    title: Pengantar
  - 
    title: Make a pencil
  - 
    title: Pensil berwarna
    completion:
      - engaged
  - 
    title: 'Challenge: more pencils'
    challenge: true
  - 
    title: Undo mistakes
  - 
    title: Change the pencil width
    completion:
      - internal
  - 
    title: 'Challenge: keyboard commands'
    challenge: true
  - 
    title: What next?
