---
title: Kotak Lukis
hero_image: images/banner.png
listed: true
copyedit: false
description: Belajar cara membuat program lukis kamu sendiri.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Pengantar
  - 
    title: Apa yang kamu butuhkan
  - 
    title: Membuat pensil
  - 
    title: 'Pensil berwarna'
    challenge: true
  - 
    title: Membuat kesalahan
  - 
    title: Mengubah lebar pensil
  - 
    title: 'Tantangan: pintasan'
    challenge: true
  - 
    title: 'Tantangan: pensil tambahan'
