---
hero_image: images/banner.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Kotak Lukis
description: Belajar cara membuat program lukis kamu sendiri.
original_url: https://codeclubprojects.org/en-GB/scratch/paint-box
interests: art
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
- title: Pengantar
- title: Apa yang kamu butuhkan
- title: Membuat pensil
  completion:
  - engaged
- title: Pensil berwarna
- title: Membuat kesalahan
- title: Mengubah lebar pensil
  completion:
  - internal
- title: 'Tantangan: pintasan'