---
title: Paint box
hero_image: imatges / banner.png
listed: true
copyedit: false
description: Fes el teu propi programa de pintura
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Introducció
  - 
    title: Make a pencil
  - 
    title: Llapis de colors
  - 
    title: 'Repte: dreceres'
    challenge: true
  - 
    title: Undo mistakes
  - 
    title: Change the pencil width
  - 
    title: 'Repte: més llapis'
    challenge: true
  - 
    title: Test yourself
  - 
    title: 'What next?'
