---
hero_image: imatges / banner.png
theme: violeta
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, disseny-0, programació-1, phys-comp-0, fabricació-0, comunitat-0
title: Caixa de pintura
description: Aprèn a fer el teu propi programa de pintura.
original_url: https://codeclubprojects.org/ca-GB/scratch/paint-box
interests: art
technologies: scratch
site_areas: projectes
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducció
  - 
    title: Què necessitaràs
  - 
    title: Fer un llapis
  - 
    title: Llapis de colors
  - 
    title: Cometre errors
  - 
    title: Canviar l'amplada del llapis
  - 
    title: 'Repte: dreceres'
  - 
    title: 'Repte: més llapis'
