---
title: Caixa de pintura
hero_image: images/banner.png
listed: true
copyedit: false
description: Fes el teu propi programa de pintura
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Introducció
  - 
    title: Feu un llapis
  - 
    title: Llapis de colors
  - 
    title: 'Repte: dreceres'
    challenge: true
  - 
    title: Desfés els errors
  - 
    title: Canvieu l'amplada del llapis
  - 
    title: 'Repte: més llapis'
    challenge: true
  - 
    title: Prova-ho tu mateix
  - 
    title: 'I ara què ve?'
