---
title: Barvice
hero_image: images/banner.png
listed: true
copyedit: false
description: Ustvari svoj risarski program
version: 4.1.0
last_tested: 2018-11-30
steps:
- title: Uvod
  completion: engaged
- title: Ustvari svinčnik
- title: Barvice
- title: 'Izziv: več svinčnikov'
  challenge: true
- title: Razveljavitev napak
  completion: internal
- title: Spremeni širino pisala
- title: 'Izziv: ukazi na tipkovnici'
  challenge: true
- title: Kaj sledi?
