---
title: Paint box
hero_image: images / banner.png
listed: true
copyedit: false
description: Naredite svoj program barv
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Uvod
  - 
    title: Naredi svinčnik
  - 
    title: Barvni svinčniki
  - 
    title: 'Izziv: bližnjice'
    challenge: true
  - 
    title: Razveljavi napake
  - 
    title: Spremenite širino svinčnika
  - 
    title: 'Izziv: več svinčnikov'
    challenge: true
  - 
    title: 'Kaj je naslednje?'
