---
title: Barvice
hero_image: images / banner.png
listed: true
copyedit: false
description: Ustvari svoj risarski program
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Uvod
  - 
    title: Ustvari svinčnik
  - 
    title: Barvni svinčniki
  - 
    title: 'Izziv: bližnjice'
    challenge: true
  - 
    title: Razveljavi napake
  - 
    title: Spremeni širino svinčnika
  - 
    title: 'Izziv: več svinčnikov'
    challenge: true
  - 
    title: Preizkusi se
  - 
    title: 'Kaj sledi?'
