---
title: Festékes doboz
hero_image: images/banner.png
listed: true
copyedit: false
description: Készítsd el a saját rajzoló programod
version: 4.1.0
last_tested: 2018-11-30
steps:
- title: Bevezetés
- title: Készíts egy ceruzát
- title: Színes ceruzák
  completion:
  - engaged
- title: 'Kihívás:  több ceruza'
  challenge: true
- title: A hibák visszavonása
- title: Módosítsd a vonal vastagságát
  completion:
  - internal
- title: 'Kihívás: billentyűzet parancsok'
  challenge: true