---
title: Festékes doboz
hero_image: images/banner.png
listed: true
copyedit: false
description: Készítsd el a saját rajzoló programod
version: 4.1.0
last_tested: 2018-11-30
steps:
  - title: Bevezetés
  - title: Készíts egy ceruzát
  - title: Színes ceruzák
  - title: 'Kihívás: parancsikonok'
    challenge: true
  - title: A hibák visszavonása
  - title: Változtasd a ceruza vastagságát
  - title: 'Kihívás: billentyűzet parancsok'
    challenge: true
  - title: Teszteld magad
  - title: 'Mi a következő lépés?'
