---
title: Caja de pintar
hero_image: images/banner.png
listed: true
copyedit: false
description: Haz tu propio programa para pintar
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Introducción
  - 
    title: Haz un lápiz
  - 
    title: Lápices de colores
  - 
    title: 'Desafío: atajos'
    challenge: true
  - 
    title: Deshacer errores
  - 
    title: Cambia el grosor del lápiz
  - 
    title: 'Desafío: comandos del teclado'
    challenge: true
  - 
    title: '¿Qué sigue?'
