---
title: Caja de pintar
hero_image: images/banner.png
listed: true
copyedit: false
description: Haz tu propio programa para pintar
version: 4.1.0
last_tested: 2018-11-30
steps:
- title: Introducción
- title: Haz un lápiz
- title: Lápices de colores
  completion:
  - engaged
- title: 'Desafío: más lápices'
  challenge: true
- title: Deshacer errores
- title: Cambia el ancho del lápiz
  completion:
  - internal
- title: 'Desafío: comandos del teclado'
  challenge: true