---
title: Kolorowe kredki
hero_image: images / banner.png
listed: true
copyedit: false
description: Naucz się, jak przygotować własny program do rysowania!
version: 4.1.0
last_tested: 30 listopada 2018
steps:
  - 
    title: Wprowadzenie
  - 
    title: Stwórz ołówek
  - 
    title: Kredki
  - 
    title: 'Wyzwanie: skróty'
    challenge: true
  - 
    title: Cofnij błędy
  - 
    title: Zmień szerokość ołówka
  - 
    title: 'Wyzwanie: więcej ołówków'
    challenge: true
  - 
    title: 'Co dalej?'
