---
title: Skicár
hero_image: images/banner.png
listed: true
copyedit: false
description: V tomto projekte si vytvoríš svoj vlastný program na kreslenie!
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Úvod
  - 
    title: Vytvorenie ceruzky
  - 
    title: Farebné ceruzky
  - 
    title: 'Výzva: viac ceruziek'
    challenge: true
  - 
    title: Mazanie a gumovanie
  - 
    title: Zmena hrúbky ceruzky
  - 
    title: 'Výzva: klávesové skratky'
    challenge: true
  - 
    title: 'Čo ďalej?'
