---
hero_image: imej / banner.png
theme: ungu
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, reka bentuk-0, pengaturcaraan-1, phys-comp-0, pembuatan-0, komuniti-0
title: Kotak Cat
description: Ketahui cara membuat program cat anda sendiri.
original_url: https://codeclubprojects.org/en-GB/scratch/paint-box
interests: seni
technologies: awal
site_areas: projek
hardware: ''
software: awal
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Pengenalan
  - 
    title: Apa yang anda perlukan
  - 
    title: Membuat pensil
  - 
    title: Pensel warna
  - 
    title: Membuat kesilapan
  - 
    title: Menukar lebar pensel
  - 
    title: 'Cabaran: pintasan'
  - 
    title: 'Cabaran: lebih banyak pensel'
