---
title: Paint box
hero_image: imej / banner.png
listed: true
copyedit: false
description: Make your own paint program
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Pengenalan
  - 
    title: Make a pencil
  - 
    title: Coloured pencils
  - 
    title: 'Challenge: shortcuts'
    challenge: true
  - 
    title: Undo mistakes
  - 
    title: Change the pencil width
  - 
    title: 'Challenge: more pencils'
    challenge: true
  - 
    title: Test yourself
  - 
    title: 'What next?'
