---
title: Kutija sa bojama
hero_image: images/banner.png
listed: true
copyedit: false
description: Nauči kako da napraviš sopstveni program za crtanje.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Šta će ti biti potrebno
  - 
    title: Pravljenje olovke
  - 
    title: 'Olovke u bojama'
    challenge: true
  - 
    title: Greške
  - 
    title: Promjena debljine olovke
  - 
    title: 'Izazov: prečice'
    challenge: true
  - 
    title: 'Izazov: više olovaka'
