---
title: Kutija sa bojama
hero_image: images/banner.png
listed: true
copyedit: false
description: Napravi sopstveni program za crtanje
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Uvod
  - 
    title: Šta će ti biti potrebno
  - 
    title: Olovke u bojama
  - 
    title: 'Izazov: prečice'
    challenge: true
  - 
    title: Greške
  - 
    title: Promjena debljine olovke
  - 
    title: 'Izazov: više olovaka'
    challenge: true
  - 
    title: 'Izazov: pravljenje više blokova'
