---
title: Boîte de peinture
hero_image: images/banner.png
listed: true
copyedit: false
description: Apprend à faire ton propre programme de dessin.
version: 4
last_tested: 2018-11-30
steps:
  - 
    title: Introduction
  - 
    title: Ce dont tu auras besoin
  - 
    title: Crayons de couleurs
  - 
    title: 'Défi : raccourcis'
    challenge: true
  - 
    title: Faire des erreurs
  - 
    title: Changer l'épaisseur du trait
  - 
    title: 'Défi : plus de crayons'
    challenge: true
  - 
    title: 'Défi : plus de crayons'
  - 
    title: 'What next?'
