---
title: Palette de peinture
hero_image: images/banner.png
listed: true
copyedit: false
description: Apprend à faire ton propre programme de dessin.
version: 4.1.0
last_tested: 2018-11-30
steps:
- title: Introduction
- title: Crée un crayon
- title: Crayons de couleurs
  completion:
  - engaged
- title: 'Défi : plus de crayons'
  challenge: true
- title: Annule les erreurs
- title: Change la largeur du stylo
  completion:
  - internal
- title: 'Défi : commandes au clavier'
  challenge: true
- title: Que faire ensuite ?
