hero_image: images/paint-box.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Boîte à couleurs
description: Apprends à programmer ton propre programme de dessin!
original_url: https://projects.raspberrypi.org/en/projects/paint-box
interests: art
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Fabrication d'un crayon
- title: Stylos colorés
- title: Erreurs de fabrication
- title: Changement de la largeur du crayon
- title: "Défi : Raccourcis"
- title: "Défi : Plus de stylos"