---
title: Palette de peinture
hero_image: images/banner.png
listed: true
copyedit: false
description: Apprend à faire ton propre programme de dessin.
version: 4.1.0
last_tested: 2018-11-30
steps:
- title: Introduction
  completion: engaged
- title: Crée un crayon
- title: Crayons de couleurs
- title: 'Défi : plus de crayons'
  challenge: true
- title: Annule les erreurs
  completion: internal
- title: Change la largeur du stylo
- title: 'Défi : commandes au clavier'
  challenge: true
- title: Que faire ensuite ?
