---
title: Scatola dei Colori
hero_image: images/banner.png
listed: true
copyedit: false
description: Crea un programma per disegnare
version: 4.1.0
last_tested: 2018-30-01
steps:
- title: Introduzione
  completion: engaged
- title: Di cosa avrai bisogno
- title: Matite colorate
- title: 'Sfida: Più matite'
  challenge: true
- title: Fare errori
  completion: internal
- title: Cambiare lo spessore della penna
- title: 'Sfida: comandi da tastiera'
  challenge: true
- title: E poi?
