hero_image: images/paint-box.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Scatola dei Colori
description: Impara a creare il tuo programma per pitturare.
original_url: https://projects.raspberrypi.org/en/projects/paint-box
interests: art
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduzione
- title: Creare una matita
- title: Penne colorate
- title: Fare errori
- title: Cambiare la larghezza della matita
- title: "Sfida: Scorciatoie"
- title: "Sfida: Altre penne"