---
title: Scatola dei Colori
hero_image: images/banner.png
listed: true
copyedit: false
description: Impara a creare il tuo programma di disegno.
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Creare una matita
  - 
    title: 'Matite colorate'
    challenge: true
  - 
    title: Fare errori
  - 
    title: Cambiare lo spessore della matita
  - 
    title: 'Sfida: Scorciatoie'
    challenge: true
  - 
    title: 'Sfida: Più matite'
