---
title: තීන්ත(paint) කොටුව(box)
hero_image: images / banner.png
listed: true
copyedit: false
description: ඔබේම තීන්ත(paint) වැඩසටහනක්(program එකක්) සාදන්න
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: හැදින්වීම
  - 
    title: පැන්සලක් සාදන්න
  - 
    title: වර්ණ පැන්සල්
  - 
    title: 'Challenge: කෙටිමං(shortcuts)'
    challenge: true
  - 
    title: වැරදීම්(mistakes) අහෝසි(undo) කරන්න
  - 
    title: පැන්සල් තුඩේ පළල වෙනස් කරන්න
  - 
    title: 'Challenge: තවත් පැන්සල්'
    challenge: true
  - 
    title: 'What next?'
