---
title: Boya kutusu
hero_image: images/banner.png
listed: true
copyedit: false
description: Kendi paint programınızı yapın
version: 4.1.0
last_tested: 2018-11-30
steps:
  - 
    title: Giriş
  - 
    title: Kalem yapmak
  - 
    title: Renkli kalemler
  - 
    title: 'Zorluk: kısayollar'
    challenge: true
  - 
    title: Hataları geri al
  - 
    title: Kalem genişliğini değiştirin
  - 
    title: 'Zorluk: daha fazla kalem'
    challenge: true
  - 
    title: Test yourself
  - 
    title: 'What next?'
